---

- name: Install package "git"
  become: true
  ansible.builtin.apt:
    name:
      - git
    state: present

- name: Check if dotfiles are present
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cfg"
  register: dotfiles

- name: Clone root dotfiles
  ansible.builtin.git:
    repo: "{{ user_root_dotfiles }}"
    accept_hostkey: true
    dest: "{{ ansible_env.HOME }}/.cfg"
    version: main
    bare: true
  register: gitclone
  changed_when: gitclone.changed and gitclone.before == none
  when: not dotfiles.stat.exists
  notify:
    - Checkout root dotfiles

- name: Update root dotfiles  # noqa command-instead-of-module
  ansible.builtin.shell: >
    git --git-dir="{{ ansible_env.HOME }}/.cfg" --work-tree="{{ ansible_env.HOME }}" pull
  args:
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash
  register: git_pull_dotfiles
  changed_when: '" up to date." not in git_pull_dotfiles.stdout'
  when: dotfiles.stat.exists

- name: Add read bash config files in ~/.bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "^for rc in \\${HOME}/.config/dotfiles/bash/"
    line: 'for rc in ${HOME}/.config/dotfiles/bash/*.sh; do [ -f "${rc}" ] && source ${rc}; done'
    state: present
    insertafter: EOF

- name: Add read config files in ~/.ssh/config
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    regexp: "^Include ~/.ssh/config.d"
    line: "Include ~/.ssh/config.d/*"
    state: present
    insertbefore: BOF
    create: true
    mode: "u=rw,go=r"

- name: Create git config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
    mode: "u=rwx,go=rx"

- name: Configure user in git
  ansible.builtin.template:
    src: git-config-user.j2
    dest: "{{ ansible_env.HOME }}/.config/git/config-user"
    mode: "u=rw,go=r"

- name: Install package packages for user root
  become: true
  ansible.builtin.apt:
    name:
      - apache2-utils        # for htpasswd
      - atop
      - bash-completion
      - bc
      - curl
      - dnsutils             # for dig,nslookup
      - dos2unix
      - git
      - htop
      - httpie
      - iftop
      - iotop
      - ipcalc
      - iperf3
      - jq
      - lsof
      - most
      - mtr-tiny             # for mtr
      - net-tools            # for arp
      - pwgen
      - sudo
      - tig
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - whois                # for mkpasswd
      - xauth                # enabling ssh -X
      - zip
      - zsh
    state: present

...
