---

- name: Install package "git"
  become: true
  ansible.builtin.apt:
    name:
      - git
    state: present

- name: Check if dotfiles are present
  become: true
  ansible.builtin.stat:
    path: '~{{ ansible_become_user | default("root") }}/.cfg'
  register: dotfiles

- name: Clone root dotfiles
  become: true
  ansible.builtin.git:
    repo: '{{ user_root_dotfiles }}'
    accept_hostkey: true
    dest: '~{{ ansible_become_user | default("root") }}/.cfg'
    version: main
    bare: true
  register: gitclone
  changed_when: gitclone.changed and gitclone.before == none
  when: not dotfiles.stat.exists
  notify:
    - Checkout root dotfiles

- name: Check if dotfiles are created
  become: true
  ansible.builtin.stat:
    path: '~{{ ansible_become_user | default("root") }}/.cfg'
  register: dotfiles

- name: Setting home directory of root
  ansible.builtin.set_fact:
    root_home: '{{ dotfiles.stat.path | dirname }}'

- name: Update root dotfiles  # noqa command-instead-of-module
  become: true
  ansible.builtin.shell: >
    git --git-dir='{{ root_home }}/.cfg' --work-tree='{{ root_home }}' pull
  args:
    chdir: '{{ root_home }}/'
    executable: /usr/bin/bash
  register: git_pull_dotfiles
  changed_when: '" up to date." not in git_pull_dotfiles.stdout'
  when: dotfiles.stat.exists

- name: Add read bash config files in ~/.bashrc
  become: true
  ansible.builtin.lineinfile:
    dest: '{{ root_home }}/.bashrc'
    regexp: '^for rc in \\${HOME}/.config/dotfiles/bash/'
    line: 'for rc in ${HOME}/.config/dotfiles/bash/*.sh; do [ -f "${rc}" ] && source ${rc}; done'
    state: present
    insertafter: EOF

- name: Add read config files in ~/.ssh/config
  become: true
  ansible.builtin.lineinfile:
    dest: '{{ root_home }}/.ssh/config'
    regexp: '^Include ~/.ssh/config.d'
    line: 'Include ~/.ssh/config.d/*'
    state: present
    insertbefore: BOF
    create: true
    mode: '0644'

- name: Create git config directory
  become: true
  ansible.builtin.file:
    path: '{{ root_home }}/.config/git'
    state: directory
    mode: '0755'

- name: Configure user in git
  become: true
  ansible.builtin.template:
    src: git-config-user.j2
    dest: '{{ root_home }}/.config/git/config-user'
    mode: '0644'

- name: Install package packages for user root
  become: true
  ansible.builtin.apt:
    name:
      - apache2-utils        # for htpasswd
      - atop
      - bash-completion
      - bc
      - curl
      - dnsutils             # for dig,nslookup
      - dos2unix
      - git
      - htop
      - httpie
      - iftop
      - iotop
      - ipcalc
      - iperf3
      - lsof
      - most
      - mtr-tiny             # for mtr
      - net-tools            # for arp
      - nvme-cli
      - pwgen
      - sudo
      - tree
      - unzip
      - vim
      - wget
      - whois                # for mkpasswd
      - xauth                # enabling ssh -X
      - zip
      - zsh
    state: present

- name: Ensure SSH keys
  become: true
  ansible.posix.authorized_key:
    user: '{{ ansible_become_user | default("root") }}'
    state: present
    key: '{{ user_root_public_keys }}'
  when: user_root_public_keys is defined

...
