---

- name: Checkout root dotfiles
  become: true
  vars:
    git_parameters: >-
      --git-dir="{{ root_home }}/.cfg" --work-tree="{{ root_home }}/"
  ansible.builtin.command: "{{ item }}"
  with_items:
    - git {{ git_parameters }} checkout
    - git {{ git_parameters }} config --local status.showUntrackedFiles no
    - git {{ git_parameters }} config --local user.name {{ user_root_name }}
    - git {{ git_parameters }} config --local user.email {{ user_root_email }}
    - git {{ git_parameters }} push --set-upstream origin main
  when: gitclone.changed and gitclone.before == none

...
