---

#
# Set keyboard layout
#
- name: Get keyboard layout
  ansible.builtin.command: localectl status
  register: localectl_status
  changed_when: "'VC Keymap: ' + setup_keymap_string not in localectl_status.stdout"

- name: Set keyboard layout
  become: true
  ansible.builtin.command:
    localectl set-x11-keymap {{ setup_keymap }} pc105 {{ setup_keymap_variant }}
  when: "'VC Keymap: ' + setup_keymap_string not in localectl_status.stdout"
  changed_when: true

...
