---

#- debug: var=hostvars[inventory_hostname]

#
# Set hostname and update `/etc/hosts`
#
- name: Set hostname (1/2)
  become: true
  ansible.builtin.hostname:
    name: "{{ setup_hostname }}"
  notify: Reboot host

- name: Set hostname (2/2)
  become: true
  ansible.builtin.copy:
    content: "{{ setup_hostname }}{{ '\n' }}"
    dest: /etc/hostname
    mode: '0644'
  notify: Reboot host

- name: Update "/etc/hosts"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address | replace('.','\\.') }}"
    line: "{{ ansible_default_ipv4.address }}{{ '\t' }}{{ setup_fqdn }}{{ '\t' }}{{ setup_hostname }}"
    state: present
  when: "'notest' not in ansible_skip_tags"

#
# Set timezone
# Under Molecule 'hwclock' is not available
#
- name: Package 'tzdata' is needed
  ansible.builtin.apt:
    name: tzdata
    state: present

- name: Set timezone
  become: true
  community.general.timezone:
    hwclock: UTC
    name: "{{ setup_timezone }}"
  when: "'notest' not in ansible_skip_tags"

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ setup_timezone }}"
  when: "'notest' in ansible_skip_tags"

#
# Set keyboard layout
# Only if not in Molecule
#
- name: Set keyboard layout
  ansible.builtin.include_tasks:
    file: keyboard.yml
  when: "'notest' not in ansible_skip_tags"

#
# Set locale
# Only if not in Molecule
#
- name: Set locale
  ansible.builtin.include_tasks:
    file: locale.yml
  when: "'notest' not in ansible_skip_tags"

...
