---

postfix_email_root: "admin@example.org"

postfix_masquerade_domains: "example.org"

postfix_relayhost: "smtp.example.org"

postfix_config: "/etc/postfix/main.cf"

postfix_mailname: "/etc/mailname"

postfix_canonical_classes:
  "envelope_sender, envelope_recipient, header_sender, header_recipient"

postfix_database_type: "hash"
postfix_canonical_map: "/etc/postfix/canonical"

postfix_inet_protocols: "ipv4"
postfix_masquerade_classes:
  "envelope_sender, envelope_recipient, header_sender, header_recipient"
postfix_masquerade_exceptions: ""

postfix_mydestination: ""
postfix_myorigin: "{{ postfix_mailname }}"

...
