---

#
# Setup computer
#

- name: Setup computer
  hosts: '{{ target | default("all") }}'
  gather_facts: true
  vars_files:
    - hostname-ip.yml

  tasks:

    - name: Block dreknix.setup
      tags:
        - setup
      block:

        - name: Block dreknix.setup.hostname
          when: setup_configure_hostname | default(true) | bool
          tags:
            - setup_hostname
          block:
            - name: Include role dreknix.setup.hostname
              ansible.builtin.include_role:
                name: dreknix.setup.hostname

        - name: Block dreknix.setup.keyboard
          when: setup_configure_keyboard | default(true) | bool
          tags:
            - setup_keyboard
          block:
            - name: Include role dreknix.setup.keyboard
              ansible.builtin.include_role:
                name: dreknix.setup.keyboard

        - name: Block dreknix.setup.locale
          when: setup_configure_locale | default(true) | bool
          tags:
            - setup_locale
          block:
            - name: Include role dreknix.setup.locale
              ansible.builtin.include_role:
                name: dreknix.setup.locale

        - name: Block dreknix.setup.timezone
          when: setup_configure_timezone | default(true) | bool
          tags:
            - setup_timezone
          block:
            - name: Include role dreknix.setup.timezone
              ansible.builtin.include_role:
                name: dreknix.setup.timezone

        - name: Block dreknix.setup.timesyncd
          when: setup_configure_timesyncd | default(true) | bool
                and 'timesyncd_clients' in group_names
          tags:
            - setup_timesyncd
          block:
            - name: Include role dreknix.setup.timesyncd
              ansible.builtin.include_role:
                name: dreknix.setup.timesyncd

        - name: Block dreknix.setup.sshd
          when: setup_configure_sshd | default(true) | bool
          tags:
            - setup_sshd
          block:
            - name: Include role dreknix.setup.sshd
              ansible.builtin.include_role:
                name: dreknix.setup.sshd

        - name: Block dreknix.setup.krb5
          when: setup_configure_krb5 | default(false) | bool
          tags:
            - setup_krb5
          block:
            - name: Include role dreknix.setup.krb5
              ansible.builtin.include_role:
                name: dreknix.setup.krb5

        - name: Block dreknix.setup.postfix
          when: setup_configure_postfix | default(true) | bool
          tags:
            - setup_postfix
          block:
            - name: Include role dreknix.setup.postfix
              ansible.builtin.include_role:
                name: dreknix.setup.postfix

        - name: Block dreknix.setup.user_root
          when: setup_configure_user_root | default(true) | bool
          tags:
            - setup_user_root
          block:
            - name: Include role dreknix.setup.user_root
              ansible.builtin.include_role:
                name: dreknix.setup.user_root

        - name: Block dreknix.setup.upgrade
          when: setup_configure_upgrade | default(true) | bool
          tags:
            - setup_upgrade
          block:
            - name: Include role dreknix.setup.upgrade
              ansible.builtin.include_role:
                name: dreknix.setup.upgrade

...
