---

#
# Setup computer
#

- name: Setup computer
  hosts: '{{ target | default("all") }}'
  gather_facts: true

  roles:

    - role: dreknix.setup.config
      tags:
        - setup
        - setup_config

    - role: dreknix.setup.upgrade
      tags:
        - setup
        - setup_upgrade

...
