---

#
# Setup computer
#

- name: Setup computer
  hosts: '{{ target | default("all") }}'
  gather_facts: true

  roles:

    - role: dreknix.setup.hostname
      tags:
        - setup
        - setup_hostname

    - role: dreknix.setup.keyboard
      tags:
        - setup
        - setup_keyboard

    - role: dreknix.setup.locale
      tags:
        - setup
        - setup_locale

    - role: dreknix.setup.timezone
      tags:
        - setup
        - setup_timezone

    - role: dreknix.setup.upgrade
      tags:
        - setup
        - setup_upgrade

...
