---

- name: Install package "systemd-timesyncd"
  become: true
  ansible.builtin.apt:
    name:
      - systemd-timesyncd
    state: present

- name: Create systemd-timesyncd directory
  become: true
  ansible.builtin.file:
    path: "{{ timesyncd_config_dir }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: Write systemd-timesyncd configuration
  become: true
  ansible.builtin.template:
    src: timesyncd-local.conf.j2
    dest: "{{ timesyncd_config_file }}"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - Restart systemd-timesyncd

...
